[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Dear ImGui Demo]
Pos=6,33
Size=533,346
Collapsed=0

[Window][Test Window]
Pos=847,85
Size=320,357
Collapsed=0

[Window][Inspector]
Pos=464,210
Size=392,487
Collapsed=0

[Window][Hi!]
Pos=128,153
Size=279,332
Collapsed=0

[Window][Chosen name]
Pos=239,92
Size=193,48
Collapsed=0

[Window][Settings]
Pos=784,489
Size=507,107
Collapsed=0

